site_name: misspy
copyright: "&copy; 2023 sonyakun"
repo_url: https://github.com/sonyakun/misspy
repo_name: sonyakun/misspy

theme:
  name: material
  palette:
    - scheme: default
      primary: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  search:
    lang: 'ja'

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Japanese
      link: /
      lang: ja

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: true
  - pymdownx.keys
  - admonition
  - pymdownx.superfences
  - pymdownx.details
